//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squizz.Platform.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Squizz.Platform.API.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to an issue with connecting to the platform&apos;s servers. Check that your internet connection is available and no other networking issues are occurring..
        /// </summary>
        internal static string SERVER_ERROR_CONNECTION {
            get {
                return ResourceManager.GetString("SERVER_ERROR_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to supplier organisation&apos;s customer account not having any On Account payment method set..
        /// </summary>
        internal static string SERVER_ERROR_CUSTOMER_ACCOUNT_NO_ACCOUNT_PAYMENT_TYPE {
            get {
                return ResourceManager.GetString("SERVER_ERROR_CUSTOMER_ACCOUNT_NO_ACCOUNT_PAYMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the customer account in the supplier&apos;s organisation being on hold and not allowing for further trading activity..
        /// </summary>
        internal static string SERVER_ERROR_CUSTOMER_ACCOUNT_ON_HOLD {
            get {
                return ResourceManager.GetString("SERVER_ERROR_CUSTOMER_ACCOUNT_ON_HOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the customer account&apos;s balance in the supplier&apos;s organisation being over the allowed limit. Not further trading can occur with the account until payments have been made against the account&apos;s balance..
        /// </summary>
        internal static string SERVER_ERROR_CUSTOMER_ACCOUNT_OUTSIDE_BALANCE_LIMIT {
            get {
                return ResourceManager.GetString("SERVER_ERROR_CUSTOMER_ACCOUNT_OUTSIDE_BALANCE_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the data import being aborted. It may have been aborted by a person or by the platform..
        /// </summary>
        internal static string SERVER_ERROR_DATA_IMPORT_ABORTED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_DATA_IMPORT_ABORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to another data import already running or the API is busy processing other requests..
        /// </summary>
        internal static string SERVER_ERROR_DATA_IMPORT_BUSY {
            get {
                return ResourceManager.GetString("SERVER_ERROR_DATA_IMPORT_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the maximum number of data imports being run over a short period of time. Wait a while before calling the endpoint again and consider calling the endpoint less often..
        /// </summary>
        internal static string SERVER_ERROR_DATA_IMPORT_MAX_IMPORTS_RUNNING {
            get {
                return ResourceManager.GetString("SERVER_ERROR_DATA_IMPORT_MAX_IMPORTS_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to no data type set indicating the kind of data being imported..
        /// </summary>
        internal static string SERVER_ERROR_DATA_IMPORT_MISSING_IMPORT_TYPE {
            get {
                return ResourceManager.GetString("SERVER_ERROR_DATA_IMPORT_MISSING_IMPORT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to an incorrect or unsupported data type being set..
        /// </summary>
        internal static string SERVER_ERROR_DATA_IMPORT_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERVER_ERROR_DATA_IMPORT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the data being imported in the JSON data format not able to be processed, because it has not been correctly formed. Check for syntax errors with the JSON data..
        /// </summary>
        internal static string SERVER_ERROR_DATA_JSON_MALFORMED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_DATA_JSON_MALFORMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the content type in the request headers not being set to application/json, specifying that data imported is in the JSON data format..
        /// </summary>
        internal static string SERVER_ERROR_DATA_JSON_WRONG_CONTENT_TYPE {
            get {
                return ResourceManager.GetString("SERVER_ERROR_DATA_JSON_WRONG_CONTENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the Ecommerce Standards Document uploaded missing an opening bracket in its JSON data..
        /// </summary>
        internal static string SERVER_ERROR_ESD_DOCUMENT_HEADER_MALFORMED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ESD_DOCUMENT_HEADER_MALFORMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the Ecommerce Standards Document being uploaded missing the dataRecords attribute that should contain the record data to import..
        /// </summary>
        internal static string SERVER_ERROR_ESD_DOCUMENT_HEADER_MISSING_ATTRIBUTES {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ESD_DOCUMENT_HEADER_MISSING_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to Ecommerce Standards Document not containing any records to import. Look to add one or more records to the document..
        /// </summary>
        internal static string SERVER_ERROR_ESD_DOCUMENT_NO_RECORD {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ESD_DOCUMENT_NO_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to Ecommerce Standards Document failing to import. Check that the document was correctly formed..
        /// </summary>
        internal static string SERVER_ERROR_ESD_DOCUMENT_UNSUCCESSFUL {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ESD_DOCUMENT_UNSUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to incorrect API credentials being given for the organisation..
        /// </summary>
        internal static string SERVER_ERROR_INCORRECT_API_CREDENTIALS {
            get {
                return ResourceManager.GetString("SERVER_ERROR_INCORRECT_API_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the data type specified not being supported or of the correct type..
        /// </summary>
        internal static string SERVER_ERROR_INCORRECT_DATA_TYPE {
            get {
                return ResourceManager.GetString("SERVER_ERROR_INCORRECT_DATA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API, due to the wrong type of record being given..
        /// </summary>
        internal static string SERVER_ERROR_INCORRECT_RECORD_TYPE {
            get {
                return ResourceManager.GetString("SERVER_ERROR_INCORRECT_RECORD_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the organisation having insufficient trading tokens in the platform to process the request..
        /// </summary>
        internal static string SERVER_ERROR_INSUFFICIENT_CREDIT {
            get {
                return ResourceManager.GetString("SERVER_ERROR_INSUFFICIENT_CREDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API, due to the endpoint being called not being found or no longer existing..
        /// </summary>
        internal static string SERVER_ERROR_INVALID_API_ACTION {
            get {
                return ResourceManager.GetString("SERVER_ERROR_INVALID_API_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to an incorrect notification category been given to it..
        /// </summary>
        internal static string SERVER_ERROR_INVALID_NOTIFICATION_CATEGORY {
            get {
                return ResourceManager.GetString("SERVER_ERROR_INVALID_NOTIFICATION_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to a line within the invoice not able to be matched up to one of the customer&apos;s products, labour, or downloads..
        /// </summary>
        internal static string SERVER_ERROR_INVOICE_LINE_NOT_MAPPED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_INVOICE_LINE_NOT_MAPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to a line&apos;s taxcode within the invoice not able to be matched up to one of the customer&apos;s taxcodes..
        /// </summary>
        internal static string SERVER_ERROR_INVOICE_LINE_TAXCODE_NOT_MAPPED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_INVOICE_LINE_TAXCODE_NOT_MAPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to a surcharge within the invoice not able to the matched up to one of the customer&apos;s surcharges..
        /// </summary>
        internal static string SERVER_ERROR_INVOICE_SURCHARGE_NOT_MAPPED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_INVOICE_SURCHARGE_NOT_MAPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to a surcharge&apos;s taxcode within the invoice not able to be matched up to one of the customer&apos;s taxcodes..
        /// </summary>
        internal static string SERVER_ERROR_INVOICE_SURCHARGE_TAXCODE_NOT_MAPPED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_INVOICE_SURCHARGE_TAXCODE_NOT_MAPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to an IO (Reading or Writing) error..
        /// </summary>
        internal static string SERVER_ERROR_IO {
            get {
                return ResourceManager.GetString("SERVER_ERROR_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to URL being not correctly set..
        /// </summary>
        internal static string SERVER_ERROR_MALFORMED_URL {
            get {
                return ResourceManager.GetString("SERVER_ERROR_MALFORMED_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API, due to the maximum number of searches allowed being reached within the allowed time frame. Wait a short period of time before trying to perform another search..
        /// </summary>
        internal static string SERVER_ERROR_MAX_SEARCHES_REACHED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_MAX_SEARCHES_REACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling the SQUIZZ.com&apos;s API due to no customer account able to be found. Check that it has been imported for the organisation..
        /// </summary>
        internal static string SERVER_ERROR_NO_CUSTOMER_ACCOUNT_FOUND {
            get {
                return ResourceManager.GetString("SERVER_ERROR_NO_CUSTOMER_ACCOUNT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API, due to the platform unable to receive any data from the connected business system..
        /// </summary>
        internal static string SERVER_ERROR_NO_DATA_RETURNED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_NO_DATA_RETURNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to no customer account in the supplier&apos;s organisation able to be found with the given account code..
        /// </summary>
        internal static string SERVER_ERROR_NO_ORG_CUSTOMER_ACCOUNT_ASSIGNED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_NO_ORG_CUSTOMER_ACCOUNT_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the supplier organisation having no active customer accounts assigned to the customer organistion..
        /// </summary>
        internal static string SERVER_ERROR_NO_ORG_CUSTOMER_ACCOUNT_SET {
            get {
                return ResourceManager.GetString("SERVER_ERROR_NO_ORG_CUSTOMER_ACCOUNT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to no people being configured in the organisation to receive the notification..
        /// </summary>
        internal static string SERVER_ERROR_NO_ORG_PEOPLE_TO_NOTIFY {
            get {
                return ResourceManager.GetString("SERVER_ERROR_NO_ORG_PEOPLE_TO_NOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to no supplier account in the customer&apos;s organisation able to be found with the given account code..
        /// </summary>
        internal static string SERVER_ERROR_NO_ORG_SUPPLIER_ACCOUNT_ASSIGNED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_NO_ORG_SUPPLIER_ACCOUNT_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the customer organisation having no active supplier accounts assigned to the supplier organistion..
        /// </summary>
        internal static string SERVER_ERROR_NO_ORG_SUPPLIER_ACCOUNT_SET {
            get {
                return ResourceManager.GetString("SERVER_ERROR_NO_ORG_SUPPLIER_ACCOUNT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to not being able to price one or more products in the order..
        /// </summary>
        internal static string SERVER_ERROR_ORDER_LINE_PRICING_MISSING {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORDER_LINE_PRICING_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to not being able to price a product in the supplier&apos;s organisation..
        /// </summary>
        internal static string SERVER_ERROR_ORDER_MAPPED_PRODUCT_PRICE_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORDER_MAPPED_PRODUCT_PRICE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to one or more of a supplier&apos;s products being out of stock and unable to be ordered..
        /// </summary>
        internal static string SERVER_ERROR_ORDER_MAPPED_PRODUCT_STOCK_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORDER_MAPPED_PRODUCT_STOCK_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to not being able to find a matching organisation&apos;s payment for the order..
        /// </summary>
        internal static string SERVER_ERROR_ORDER_PAYMENT_NOT_MATCHED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORDER_PAYMENT_NOT_MATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to not being able to find a matching product in the supplier&apos;s organisation..
        /// </summary>
        internal static string SERVER_ERROR_ORDER_PRODUCT_NOT_MAPPED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORDER_PRODUCT_NOT_MAPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to not being able to find a matching organisation&apos;s product for the order..
        /// </summary>
        internal static string SERVER_ERROR_ORDER_PRODUCT_NOT_MATCHED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORDER_PRODUCT_NOT_MATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to not being able to find a matching organisation&apos;s surcharge for the order..
        /// </summary>
        internal static string SERVER_ERROR_ORDER_SURCHARGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORDER_SURCHARGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to not being able to price one or more surcharges in the order..
        /// </summary>
        internal static string SERVER_ERROR_ORDER_SURCHARGE_PRICING_MISSING {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORDER_SURCHARGE_PRICING_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the organisation given not able to be found in the platform, or it is not active..
        /// </summary>
        internal static string SERVER_ERROR_ORG_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORG_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the organisation being inactive or deleted from the platform..
        /// </summary>
        internal static string SERVER_ERROR_ORG_INACTIVE {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORG_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the organisation not having enough trading tokens..
        /// </summary>
        internal static string SERVER_ERROR_ORG_NOT_ENOUGH_CREDITS {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORG_NOT_ENOUGH_CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API since no organisation could be found matching the ID given..
        /// </summary>
        internal static string SERVER_ERROR_ORG_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the organisation&apos;s Trading Status does not allow it to sell on the platform..
        /// </summary>
        internal static string SERVER_ERROR_ORG_NOT_SELLING {
            get {
                return ResourceManager.GetString("SERVER_ERROR_ORG_NOT_SELLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the payment status set for the order not being supported..
        /// </summary>
        internal static string SERVER_ERROR_PAYMENT_STATUS_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_PAYMENT_STATUS_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to permission being denied to access data, or save data, or access the endpoint..
        /// </summary>
        internal static string SERVER_ERROR_PERMISSION_DENIED {
            get {
                return ResourceManager.GetString("SERVER_ERROR_PERMISSION_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to an issue with the protocol used to call the endpoint..
        /// </summary>
        internal static string SERVER_ERROR_REQUEST_PROTOCOL {
            get {
                return ResourceManager.GetString("SERVER_ERROR_REQUEST_PROTOCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the server returning a bad response. The platform&apos;s API may be unavailable, under heavy load, or a network connection error could be occurring..
        /// </summary>
        internal static string SERVER_ERROR_RESPONSE {
            get {
                return ResourceManager.GetString("SERVER_ERROR_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the organisation&apos;s security certificate not able to found or does not exist..
        /// </summary>
        internal static string SERVER_ERROR_SECURITY_CERTIFICATE_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERVER_ERROR_SECURITY_CERTIFICATE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API, due to the common name set in the organisation&apos;s security certificate not matching the IP address of the internet connection used to call the endpoint.
        /// </summary>
        internal static string SERVER_ERROR_SENDER_DOES_NOT_MATCH_CERTIFICATE_COMMON_NAME {
            get {
                return ResourceManager.GetString("SERVER_ERROR_SENDER_DOES_NOT_MATCH_CERTIFICATE_COMMON_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when calling SQUIZZ.com&apos;s API due to the API session not existing or previously destroyed..
        /// </summary>
        internal static string SERVER_ERROR_SESSION_INVALID {
            get {
                return ResourceManager.GetString("SERVER_ERROR_SESSION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown or non-specified error occurred when calling SQUIZZ.com&apos;s API..
        /// </summary>
        internal static string SERVER_ERROR_UNKNOWN {
            get {
                return ResourceManager.GetString("SERVER_ERROR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when SQUIZZ.com&apos;s API was called..
        /// </summary>
        internal static string SERVER_FAILURE {
            get {
                return ResourceManager.GetString("SERVER_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQUIZZ.com API was successfully called..
        /// </summary>
        internal static string SERVER_SUCCESS {
            get {
                return ResourceManager.GetString("SERVER_SUCCESS", resourceCulture);
            }
        }
    }
}
